[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "velib-ml"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["numpy", "pandas", "scikit-learn", "lightgbm"]

[tool.setuptools.packages.find]
where = ["src"]